// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `board_config_from_definition`, `board_definition_error`, `game_move_from_engine`, `hash_byte`, `hash_bytes`, `illegal_move_error`, `match_hash`, `match_snapshot_from_state`, `match_state_from_snapshot`, `move_resolution_from_engine`, `move_to_engine`, `player_byte`, `seed_from_hash`, `snapshot_from_state`, `snapshot_hash`, `state_error`, `state_from_snapshot`, `tile_byte`, `win_reason_byte`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

MatchSnapshot initialMatch({required GameBoardDefinition boardDefinition}) =>
    RustLib.instance.api.crateApiInitialMatch(boardDefinition: boardDefinition);

List<GameMove> matchLegalMoves({required MatchSnapshot snapshot}) =>
    RustLib.instance.api.crateApiMatchLegalMoves(snapshot: snapshot);

MoveResult matchApplyMove({
  required MatchSnapshot snapshot,
  required GameMove gameMove,
}) => RustLib.instance.api.crateApiMatchApplyMove(
  snapshot: snapshot,
  gameMove: gameMove,
);

MatchSnapshot advanceRound({required MatchSnapshot snapshot}) =>
    RustLib.instance.api.crateApiAdvanceRound(snapshot: snapshot);

/// Chooses a move for the side to play, or `None` when the round offers
/// none.
///
/// The seed comes from the round's own hash rather than from the caller, so
/// the same position always produces the same move: a bot that cannot be
/// replayed cannot have its mistakes reported, and a seed held on the Dart
/// side would put game state in the presentation layer.
Future<GameMove?> chooseBotMove({
  required MatchSnapshot snapshot,
  required BotPolicy policy,
}) => RustLib.instance.api.crateApiChooseBotMove(
  snapshot: snapshot,
  policy: policy,
);

enum BotPolicy {
  random,
  greedy,
  minimax,
  strategic,
}

class CounterPushRestriction {
  final int pusherPieceId;
  final int pushedPieceId;

  const CounterPushRestriction({
    required this.pusherPieceId,
    required this.pushedPieceId,
  });

  @override
  int get hashCode => pusherPieceId.hashCode ^ pushedPieceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CounterPushRestriction &&
          runtimeType == other.runtimeType &&
          pusherPieceId == other.pusherPieceId &&
          pushedPieceId == other.pushedPieceId;
}

class GameBoardCell {
  final int x;
  final int y;

  const GameBoardCell({
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameBoardCell &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class GameBoardDefinition {
  final List<GameBoardCell> playableCells;
  final List<GamePiece> startingPieces;

  const GameBoardDefinition({
    required this.playableCells,
    required this.startingPieces,
  });

  @override
  int get hashCode => playableCells.hashCode ^ startingPieces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameBoardDefinition &&
          runtimeType == other.runtimeType &&
          playableCells == other.playableCells &&
          startingPieces == other.startingPieces;
}

enum GameDirection {
  up,
  down,
  left,
  right,
}

enum GameMatchPhase {
  playing,
  roundOver,
  matchOver,
}

class GameMove {
  final int pieceId;
  final GameDirection direction;

  const GameMove({
    required this.pieceId,
    required this.direction,
  });

  @override
  int get hashCode => pieceId.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameMove &&
          runtimeType == other.runtimeType &&
          pieceId == other.pieceId &&
          direction == other.direction;
}

class GamePiece {
  final int id;
  final GamePlayer owner;
  final int x;
  final int y;

  const GamePiece({
    required this.id,
    required this.owner,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => id.hashCode ^ owner.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamePiece &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          owner == other.owner &&
          x == other.x &&
          y == other.y;
}

enum GamePlayer {
  first,
  second,
}

class GameSnapshot {
  final GamePlayer currentPlayer;
  final List<GameTile> tiles;
  final List<GamePiece> pieces;
  final CounterPushRestriction? counterPush;
  final GamePlayer? winner;
  final GameWinReason? winReason;
  final String snapshotHash;

  const GameSnapshot({
    required this.currentPlayer,
    required this.tiles,
    required this.pieces,
    this.counterPush,
    this.winner,
    this.winReason,
    required this.snapshotHash,
  });

  @override
  int get hashCode =>
      currentPlayer.hashCode ^
      tiles.hashCode ^
      pieces.hashCode ^
      counterPush.hashCode ^
      winner.hashCode ^
      winReason.hashCode ^
      snapshotHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameSnapshot &&
          runtimeType == other.runtimeType &&
          currentPlayer == other.currentPlayer &&
          tiles == other.tiles &&
          pieces == other.pieces &&
          counterPush == other.counterPush &&
          winner == other.winner &&
          winReason == other.winReason &&
          snapshotHash == other.snapshotHash;
}

class GameTile {
  final int x;
  final int y;
  final GameTileKind kind;

  const GameTile({
    required this.x,
    required this.y,
    required this.kind,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameTile &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          kind == other.kind;
}

enum GameTileKind {
  normal,
  damaged,
  hole,
}

enum GameWinReason {
  knockout,
  immobilization,
}

/// A best-of-three match, carried across the bridge by value.
///
/// `starting_pieces` is the layout each round resets to. The round's own
/// tiles cannot stand in for it: they carry the damage taken since, not the
/// board a reset restores.
class MatchSnapshot {
  final GameSnapshot round;
  final List<GamePiece> startingPieces;
  final int firstPlayerWins;
  final int secondPlayerWins;
  final GameMatchPhase phase;
  final GamePlayer? roundWinner;
  final GameWinReason? roundWinReason;
  final GamePlayer? matchWinner;
  final String snapshotHash;

  const MatchSnapshot({
    required this.round,
    required this.startingPieces,
    required this.firstPlayerWins,
    required this.secondPlayerWins,
    required this.phase,
    this.roundWinner,
    this.roundWinReason,
    this.matchWinner,
    required this.snapshotHash,
  });

  @override
  int get hashCode =>
      round.hashCode ^
      startingPieces.hashCode ^
      firstPlayerWins.hashCode ^
      secondPlayerWins.hashCode ^
      phase.hashCode ^
      roundWinner.hashCode ^
      roundWinReason.hashCode ^
      matchWinner.hashCode ^
      snapshotHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchSnapshot &&
          runtimeType == other.runtimeType &&
          round == other.round &&
          startingPieces == other.startingPieces &&
          firstPlayerWins == other.firstPlayerWins &&
          secondPlayerWins == other.secondPlayerWins &&
          phase == other.phase &&
          roundWinner == other.roundWinner &&
          roundWinReason == other.roundWinReason &&
          matchWinner == other.matchWinner &&
          snapshotHash == other.snapshotHash;
}

enum MoveActionKind {
  normal,
  push,
}

class MoveResolution {
  final MoveActionKind actionKind;
  final PieceTravel mover;
  final PieceDisplacement? displaced;
  final TileTransition tileTransition;

  const MoveResolution({
    required this.actionKind,
    required this.mover,
    this.displaced,
    required this.tileTransition,
  });

  @override
  int get hashCode =>
      actionKind.hashCode ^
      mover.hashCode ^
      displaced.hashCode ^
      tileTransition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveResolution &&
          runtimeType == other.runtimeType &&
          actionKind == other.actionKind &&
          mover == other.mover &&
          displaced == other.displaced &&
          tileTransition == other.tileTransition;
}

class MoveResult {
  final MatchSnapshot snapshot;
  final MoveResolution resolution;

  const MoveResult({
    required this.snapshot,
    required this.resolution,
  });

  @override
  int get hashCode => snapshot.hashCode ^ resolution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveResult &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          resolution == other.resolution;
}

class PieceDisplacement {
  final int pieceId;
  final int fromX;
  final int fromY;
  final int? toX;
  final int? toY;
  final GameDirection? exitDirection;

  const PieceDisplacement({
    required this.pieceId,
    required this.fromX,
    required this.fromY,
    this.toX,
    this.toY,
    this.exitDirection,
  });

  @override
  int get hashCode =>
      pieceId.hashCode ^
      fromX.hashCode ^
      fromY.hashCode ^
      toX.hashCode ^
      toY.hashCode ^
      exitDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PieceDisplacement &&
          runtimeType == other.runtimeType &&
          pieceId == other.pieceId &&
          fromX == other.fromX &&
          fromY == other.fromY &&
          toX == other.toX &&
          toY == other.toY &&
          exitDirection == other.exitDirection;
}

class PieceTravel {
  final int pieceId;
  final int fromX;
  final int fromY;
  final int toX;
  final int toY;

  const PieceTravel({
    required this.pieceId,
    required this.fromX,
    required this.fromY,
    required this.toX,
    required this.toY,
  });

  @override
  int get hashCode =>
      pieceId.hashCode ^
      fromX.hashCode ^
      fromY.hashCode ^
      toX.hashCode ^
      toY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PieceTravel &&
          runtimeType == other.runtimeType &&
          pieceId == other.pieceId &&
          fromX == other.fromX &&
          fromY == other.fromY &&
          toX == other.toX &&
          toY == other.toY;
}

class TileTransition {
  final int x;
  final int y;
  final GameTileKind from;
  final GameTileKind to;

  const TileTransition({
    required this.x,
    required this.y,
    required this.from,
    required this.to,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TileTransition &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          from == other.from &&
          to == other.to;
}
