// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:ttush_push/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `game_move_from_engine`, `hash_byte`, `hash_bytes`, `illegal_move_error`, `move_to_engine`, `player_byte`, `snapshot_from_state`, `snapshot_hash`, `state_error`, `state_from_snapshot`, `tile_byte`, `win_reason_byte`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

GameSnapshot initialState() => RustLib.instance.api.crateApiInitialState();

List<GameMove> legalMoves({required GameSnapshot snapshot}) =>
    RustLib.instance.api.crateApiLegalMoves(snapshot: snapshot);

GameSnapshot applyMove({
  required GameSnapshot snapshot,
  required GameMove gameMove,
}) => RustLib.instance.api.crateApiApplyMove(
  snapshot: snapshot,
  gameMove: gameMove,
);

class CounterPushRestriction {
  const CounterPushRestriction({
    required this.pusherPieceId,
    required this.pushedPieceId,
  });
  final int pusherPieceId;
  final int pushedPieceId;

  @override
  int get hashCode => pusherPieceId.hashCode ^ pushedPieceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CounterPushRestriction &&
          runtimeType == other.runtimeType &&
          pusherPieceId == other.pusherPieceId &&
          pushedPieceId == other.pushedPieceId;
}

enum GameDirection {
  up,
  down,
  left,
  right,
}

class GameMove {
  const GameMove({
    required this.pieceId,
    required this.direction,
  });
  final int pieceId;
  final GameDirection direction;

  @override
  int get hashCode => pieceId.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameMove &&
          runtimeType == other.runtimeType &&
          pieceId == other.pieceId &&
          direction == other.direction;
}

class GamePiece {
  const GamePiece({
    required this.id,
    required this.owner,
    required this.x,
    required this.y,
  });
  final int id;
  final GamePlayer owner;
  final int x;
  final int y;

  @override
  int get hashCode => id.hashCode ^ owner.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamePiece &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          owner == other.owner &&
          x == other.x &&
          y == other.y;
}

enum GamePlayer {
  first,
  second,
}

class GameSnapshot {
  const GameSnapshot({
    required this.currentPlayer,
    required this.tiles,
    required this.pieces,
    required this.snapshotHash,
    this.counterPush,
    this.winner,
    this.winReason,
  });
  final GamePlayer currentPlayer;
  final List<GameTile> tiles;
  final List<GamePiece> pieces;
  final CounterPushRestriction? counterPush;
  final GamePlayer? winner;
  final GameWinReason? winReason;
  final String snapshotHash;

  @override
  int get hashCode =>
      currentPlayer.hashCode ^
      tiles.hashCode ^
      pieces.hashCode ^
      counterPush.hashCode ^
      winner.hashCode ^
      winReason.hashCode ^
      snapshotHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameSnapshot &&
          runtimeType == other.runtimeType &&
          currentPlayer == other.currentPlayer &&
          tiles == other.tiles &&
          pieces == other.pieces &&
          counterPush == other.counterPush &&
          winner == other.winner &&
          winReason == other.winReason &&
          snapshotHash == other.snapshotHash;
}

class GameTile {
  const GameTile({
    required this.x,
    required this.y,
    required this.kind,
  });
  final int x;
  final int y;
  final GameTileKind kind;

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameTile &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          kind == other.kind;
}

enum GameTileKind {
  normal,
  damaged,
  hole,
}

enum GameWinReason {
  knockout,
  immobilization,
}
