// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -933160049;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'engine',
        ioDirectory: 'engine/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  MatchSnapshot crateApiAdvanceRound({required MatchSnapshot snapshot});

  GameMove? crateApiChooseBotMove({
    required MatchSnapshot snapshot,
    required BotPolicy policy,
  });

  MatchSnapshot crateApiInitialMatch({
    required GameBoardDefinition boardDefinition,
  });

  MoveResult crateApiMatchApplyMove({
    required MatchSnapshot snapshot,
    required GameMove gameMove,
  });

  List<GameMove> crateApiMatchLegalMoves({required MatchSnapshot snapshot});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  MatchSnapshot crateApiAdvanceRound({required MatchSnapshot snapshot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_match_snapshot(snapshot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_match_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAdvanceRoundConstMeta,
        argValues: [snapshot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdvanceRoundConstMeta => const TaskConstMeta(
    debugName: "advance_round",
    argNames: ["snapshot"],
  );

  @override
  GameMove? crateApiChooseBotMove({
    required MatchSnapshot snapshot,
    required BotPolicy policy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_match_snapshot(snapshot, serializer);
          sse_encode_bot_policy(policy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_game_move,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChooseBotMoveConstMeta,
        argValues: [snapshot, policy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChooseBotMoveConstMeta => const TaskConstMeta(
    debugName: "choose_bot_move",
    argNames: ["snapshot", "policy"],
  );

  @override
  MatchSnapshot crateApiInitialMatch({
    required GameBoardDefinition boardDefinition,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_game_board_definition(
            boardDefinition,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_match_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitialMatchConstMeta,
        argValues: [boardDefinition],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitialMatchConstMeta => const TaskConstMeta(
    debugName: "initial_match",
    argNames: ["boardDefinition"],
  );

  @override
  MoveResult crateApiMatchApplyMove({
    required MatchSnapshot snapshot,
    required GameMove gameMove,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_match_snapshot(snapshot, serializer);
          sse_encode_box_autoadd_game_move(gameMove, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_move_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatchApplyMoveConstMeta,
        argValues: [snapshot, gameMove],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatchApplyMoveConstMeta => const TaskConstMeta(
    debugName: "match_apply_move",
    argNames: ["snapshot", "gameMove"],
  );

  @override
  List<GameMove> crateApiMatchLegalMoves({required MatchSnapshot snapshot}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_match_snapshot(snapshot, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_game_move,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatchLegalMovesConstMeta,
        argValues: [snapshot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatchLegalMovesConstMeta => const TaskConstMeta(
    debugName: "match_legal_moves",
    argNames: ["snapshot"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BotPolicy dco_decode_bot_policy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BotPolicy.values[raw as int];
  }

  @protected
  CounterPushRestriction dco_decode_box_autoadd_counter_push_restriction(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_counter_push_restriction(raw);
  }

  @protected
  GameBoardDefinition dco_decode_box_autoadd_game_board_definition(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_board_definition(raw);
  }

  @protected
  GameDirection dco_decode_box_autoadd_game_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_direction(raw);
  }

  @protected
  GameMove dco_decode_box_autoadd_game_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_move(raw);
  }

  @protected
  GamePlayer dco_decode_box_autoadd_game_player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_player(raw);
  }

  @protected
  GameWinReason dco_decode_box_autoadd_game_win_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_game_win_reason(raw);
  }

  @protected
  MatchSnapshot dco_decode_box_autoadd_match_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_match_snapshot(raw);
  }

  @protected
  PieceDisplacement dco_decode_box_autoadd_piece_displacement(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_piece_displacement(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CounterPushRestriction dco_decode_counter_push_restriction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CounterPushRestriction(
      pusherPieceId: dco_decode_u_8(arr[0]),
      pushedPieceId: dco_decode_u_8(arr[1]),
    );
  }

  @protected
  GameBoardCell dco_decode_game_board_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GameBoardCell(
      x: dco_decode_u_8(arr[0]),
      y: dco_decode_u_8(arr[1]),
    );
  }

  @protected
  GameBoardDefinition dco_decode_game_board_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GameBoardDefinition(
      playableCells: dco_decode_list_game_board_cell(arr[0]),
      startingPieces: dco_decode_list_game_piece(arr[1]),
    );
  }

  @protected
  GameDirection dco_decode_game_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameDirection.values[raw as int];
  }

  @protected
  GameMatchPhase dco_decode_game_match_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameMatchPhase.values[raw as int];
  }

  @protected
  GameMove dco_decode_game_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GameMove(
      pieceId: dco_decode_u_8(arr[0]),
      direction: dco_decode_game_direction(arr[1]),
    );
  }

  @protected
  GamePiece dco_decode_game_piece(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GamePiece(
      id: dco_decode_u_8(arr[0]),
      owner: dco_decode_game_player(arr[1]),
      x: dco_decode_u_8(arr[2]),
      y: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  GamePlayer dco_decode_game_player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GamePlayer.values[raw as int];
  }

  @protected
  GameSnapshot dco_decode_game_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GameSnapshot(
      currentPlayer: dco_decode_game_player(arr[0]),
      tiles: dco_decode_list_game_tile(arr[1]),
      pieces: dco_decode_list_game_piece(arr[2]),
      counterPush: dco_decode_opt_box_autoadd_counter_push_restriction(arr[3]),
      winner: dco_decode_opt_box_autoadd_game_player(arr[4]),
      winReason: dco_decode_opt_box_autoadd_game_win_reason(arr[5]),
      snapshotHash: dco_decode_String(arr[6]),
    );
  }

  @protected
  GameTile dco_decode_game_tile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GameTile(
      x: dco_decode_u_8(arr[0]),
      y: dco_decode_u_8(arr[1]),
      kind: dco_decode_game_tile_kind(arr[2]),
    );
  }

  @protected
  GameTileKind dco_decode_game_tile_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameTileKind.values[raw as int];
  }

  @protected
  GameWinReason dco_decode_game_win_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameWinReason.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<GameBoardCell> dco_decode_list_game_board_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_game_board_cell).toList();
  }

  @protected
  List<GameMove> dco_decode_list_game_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_game_move).toList();
  }

  @protected
  List<GamePiece> dco_decode_list_game_piece(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_game_piece).toList();
  }

  @protected
  List<GameTile> dco_decode_list_game_tile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_game_tile).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MatchSnapshot dco_decode_match_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MatchSnapshot(
      round: dco_decode_game_snapshot(arr[0]),
      startingPieces: dco_decode_list_game_piece(arr[1]),
      firstPlayerWins: dco_decode_u_8(arr[2]),
      secondPlayerWins: dco_decode_u_8(arr[3]),
      phase: dco_decode_game_match_phase(arr[4]),
      roundWinner: dco_decode_opt_box_autoadd_game_player(arr[5]),
      roundWinReason: dco_decode_opt_box_autoadd_game_win_reason(arr[6]),
      matchWinner: dco_decode_opt_box_autoadd_game_player(arr[7]),
      snapshotHash: dco_decode_String(arr[8]),
    );
  }

  @protected
  MoveActionKind dco_decode_move_action_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MoveActionKind.values[raw as int];
  }

  @protected
  MoveResolution dco_decode_move_resolution(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MoveResolution(
      actionKind: dco_decode_move_action_kind(arr[0]),
      mover: dco_decode_piece_travel(arr[1]),
      displaced: dco_decode_opt_box_autoadd_piece_displacement(arr[2]),
      tileTransition: dco_decode_tile_transition(arr[3]),
    );
  }

  @protected
  MoveResult dco_decode_move_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MoveResult(
      snapshot: dco_decode_match_snapshot(arr[0]),
      resolution: dco_decode_move_resolution(arr[1]),
    );
  }

  @protected
  CounterPushRestriction? dco_decode_opt_box_autoadd_counter_push_restriction(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_counter_push_restriction(raw);
  }

  @protected
  GameDirection? dco_decode_opt_box_autoadd_game_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_game_direction(raw);
  }

  @protected
  GameMove? dco_decode_opt_box_autoadd_game_move(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_game_move(raw);
  }

  @protected
  GamePlayer? dco_decode_opt_box_autoadd_game_player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_game_player(raw);
  }

  @protected
  GameWinReason? dco_decode_opt_box_autoadd_game_win_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_game_win_reason(raw);
  }

  @protected
  PieceDisplacement? dco_decode_opt_box_autoadd_piece_displacement(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_piece_displacement(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  PieceDisplacement dco_decode_piece_displacement(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PieceDisplacement(
      pieceId: dco_decode_u_8(arr[0]),
      fromX: dco_decode_u_8(arr[1]),
      fromY: dco_decode_u_8(arr[2]),
      toX: dco_decode_opt_box_autoadd_u_8(arr[3]),
      toY: dco_decode_opt_box_autoadd_u_8(arr[4]),
      exitDirection: dco_decode_opt_box_autoadd_game_direction(arr[5]),
    );
  }

  @protected
  PieceTravel dco_decode_piece_travel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PieceTravel(
      pieceId: dco_decode_u_8(arr[0]),
      fromX: dco_decode_u_8(arr[1]),
      fromY: dco_decode_u_8(arr[2]),
      toX: dco_decode_u_8(arr[3]),
      toY: dco_decode_u_8(arr[4]),
    );
  }

  @protected
  TileTransition dco_decode_tile_transition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TileTransition(
      x: dco_decode_u_8(arr[0]),
      y: dco_decode_u_8(arr[1]),
      from: dco_decode_game_tile_kind(arr[2]),
      to: dco_decode_game_tile_kind(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BotPolicy sse_decode_bot_policy(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BotPolicy.values[inner];
  }

  @protected
  CounterPushRestriction sse_decode_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_counter_push_restriction(deserializer));
  }

  @protected
  GameBoardDefinition sse_decode_box_autoadd_game_board_definition(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_board_definition(deserializer));
  }

  @protected
  GameDirection sse_decode_box_autoadd_game_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_direction(deserializer));
  }

  @protected
  GameMove sse_decode_box_autoadd_game_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_move(deserializer));
  }

  @protected
  GamePlayer sse_decode_box_autoadd_game_player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_player(deserializer));
  }

  @protected
  GameWinReason sse_decode_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_game_win_reason(deserializer));
  }

  @protected
  MatchSnapshot sse_decode_box_autoadd_match_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_match_snapshot(deserializer));
  }

  @protected
  PieceDisplacement sse_decode_box_autoadd_piece_displacement(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_piece_displacement(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  CounterPushRestriction sse_decode_counter_push_restriction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pusherPieceId = sse_decode_u_8(deserializer);
    var var_pushedPieceId = sse_decode_u_8(deserializer);
    return CounterPushRestriction(
      pusherPieceId: var_pusherPieceId,
      pushedPieceId: var_pushedPieceId,
    );
  }

  @protected
  GameBoardCell sse_decode_game_board_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_u_8(deserializer);
    var var_y = sse_decode_u_8(deserializer);
    return GameBoardCell(x: var_x, y: var_y);
  }

  @protected
  GameBoardDefinition sse_decode_game_board_definition(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playableCells = sse_decode_list_game_board_cell(deserializer);
    var var_startingPieces = sse_decode_list_game_piece(deserializer);
    return GameBoardDefinition(
      playableCells: var_playableCells,
      startingPieces: var_startingPieces,
    );
  }

  @protected
  GameDirection sse_decode_game_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameDirection.values[inner];
  }

  @protected
  GameMatchPhase sse_decode_game_match_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameMatchPhase.values[inner];
  }

  @protected
  GameMove sse_decode_game_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceId = sse_decode_u_8(deserializer);
    var var_direction = sse_decode_game_direction(deserializer);
    return GameMove(pieceId: var_pieceId, direction: var_direction);
  }

  @protected
  GamePiece sse_decode_game_piece(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_8(deserializer);
    var var_owner = sse_decode_game_player(deserializer);
    var var_x = sse_decode_u_8(deserializer);
    var var_y = sse_decode_u_8(deserializer);
    return GamePiece(id: var_id, owner: var_owner, x: var_x, y: var_y);
  }

  @protected
  GamePlayer sse_decode_game_player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GamePlayer.values[inner];
  }

  @protected
  GameSnapshot sse_decode_game_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentPlayer = sse_decode_game_player(deserializer);
    var var_tiles = sse_decode_list_game_tile(deserializer);
    var var_pieces = sse_decode_list_game_piece(deserializer);
    var var_counterPush = sse_decode_opt_box_autoadd_counter_push_restriction(
      deserializer,
    );
    var var_winner = sse_decode_opt_box_autoadd_game_player(deserializer);
    var var_winReason = sse_decode_opt_box_autoadd_game_win_reason(
      deserializer,
    );
    var var_snapshotHash = sse_decode_String(deserializer);
    return GameSnapshot(
      currentPlayer: var_currentPlayer,
      tiles: var_tiles,
      pieces: var_pieces,
      counterPush: var_counterPush,
      winner: var_winner,
      winReason: var_winReason,
      snapshotHash: var_snapshotHash,
    );
  }

  @protected
  GameTile sse_decode_game_tile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_u_8(deserializer);
    var var_y = sse_decode_u_8(deserializer);
    var var_kind = sse_decode_game_tile_kind(deserializer);
    return GameTile(x: var_x, y: var_y, kind: var_kind);
  }

  @protected
  GameTileKind sse_decode_game_tile_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameTileKind.values[inner];
  }

  @protected
  GameWinReason sse_decode_game_win_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameWinReason.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<GameBoardCell> sse_decode_list_game_board_cell(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GameBoardCell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_game_board_cell(deserializer));
    }
    return ans_;
  }

  @protected
  List<GameMove> sse_decode_list_game_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GameMove>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_game_move(deserializer));
    }
    return ans_;
  }

  @protected
  List<GamePiece> sse_decode_list_game_piece(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GamePiece>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_game_piece(deserializer));
    }
    return ans_;
  }

  @protected
  List<GameTile> sse_decode_list_game_tile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GameTile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_game_tile(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MatchSnapshot sse_decode_match_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_round = sse_decode_game_snapshot(deserializer);
    var var_startingPieces = sse_decode_list_game_piece(deserializer);
    var var_firstPlayerWins = sse_decode_u_8(deserializer);
    var var_secondPlayerWins = sse_decode_u_8(deserializer);
    var var_phase = sse_decode_game_match_phase(deserializer);
    var var_roundWinner = sse_decode_opt_box_autoadd_game_player(deserializer);
    var var_roundWinReason = sse_decode_opt_box_autoadd_game_win_reason(
      deserializer,
    );
    var var_matchWinner = sse_decode_opt_box_autoadd_game_player(deserializer);
    var var_snapshotHash = sse_decode_String(deserializer);
    return MatchSnapshot(
      round: var_round,
      startingPieces: var_startingPieces,
      firstPlayerWins: var_firstPlayerWins,
      secondPlayerWins: var_secondPlayerWins,
      phase: var_phase,
      roundWinner: var_roundWinner,
      roundWinReason: var_roundWinReason,
      matchWinner: var_matchWinner,
      snapshotHash: var_snapshotHash,
    );
  }

  @protected
  MoveActionKind sse_decode_move_action_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MoveActionKind.values[inner];
  }

  @protected
  MoveResolution sse_decode_move_resolution(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_actionKind = sse_decode_move_action_kind(deserializer);
    var var_mover = sse_decode_piece_travel(deserializer);
    var var_displaced = sse_decode_opt_box_autoadd_piece_displacement(
      deserializer,
    );
    var var_tileTransition = sse_decode_tile_transition(deserializer);
    return MoveResolution(
      actionKind: var_actionKind,
      mover: var_mover,
      displaced: var_displaced,
      tileTransition: var_tileTransition,
    );
  }

  @protected
  MoveResult sse_decode_move_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_snapshot = sse_decode_match_snapshot(deserializer);
    var var_resolution = sse_decode_move_resolution(deserializer);
    return MoveResult(snapshot: var_snapshot, resolution: var_resolution);
  }

  @protected
  CounterPushRestriction? sse_decode_opt_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_counter_push_restriction(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GameDirection? sse_decode_opt_box_autoadd_game_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_game_direction(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GameMove? sse_decode_opt_box_autoadd_game_move(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_game_move(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GamePlayer? sse_decode_opt_box_autoadd_game_player(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_game_player(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GameWinReason? sse_decode_opt_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_game_win_reason(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PieceDisplacement? sse_decode_opt_box_autoadd_piece_displacement(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_piece_displacement(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PieceDisplacement sse_decode_piece_displacement(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceId = sse_decode_u_8(deserializer);
    var var_fromX = sse_decode_u_8(deserializer);
    var var_fromY = sse_decode_u_8(deserializer);
    var var_toX = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_toY = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_exitDirection = sse_decode_opt_box_autoadd_game_direction(
      deserializer,
    );
    return PieceDisplacement(
      pieceId: var_pieceId,
      fromX: var_fromX,
      fromY: var_fromY,
      toX: var_toX,
      toY: var_toY,
      exitDirection: var_exitDirection,
    );
  }

  @protected
  PieceTravel sse_decode_piece_travel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceId = sse_decode_u_8(deserializer);
    var var_fromX = sse_decode_u_8(deserializer);
    var var_fromY = sse_decode_u_8(deserializer);
    var var_toX = sse_decode_u_8(deserializer);
    var var_toY = sse_decode_u_8(deserializer);
    return PieceTravel(
      pieceId: var_pieceId,
      fromX: var_fromX,
      fromY: var_fromY,
      toX: var_toX,
      toY: var_toY,
    );
  }

  @protected
  TileTransition sse_decode_tile_transition(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_u_8(deserializer);
    var var_y = sse_decode_u_8(deserializer);
    var var_from = sse_decode_game_tile_kind(deserializer);
    var var_to = sse_decode_game_tile_kind(deserializer);
    return TileTransition(x: var_x, y: var_y, from: var_from, to: var_to);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bot_policy(BotPolicy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_box_autoadd_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_counter_push_restriction(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_board_definition(
    GameBoardDefinition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_board_definition(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_direction(
    GameDirection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_direction(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_move(
    GameMove self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_move(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_player(
    GamePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_player(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_game_win_reason(
    GameWinReason self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_win_reason(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_match_snapshot(
    MatchSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_match_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_piece_displacement(
    PieceDisplacement self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_piece_displacement(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pusherPieceId, serializer);
    sse_encode_u_8(self.pushedPieceId, serializer);
  }

  @protected
  void sse_encode_game_board_cell(
    GameBoardCell self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.x, serializer);
    sse_encode_u_8(self.y, serializer);
  }

  @protected
  void sse_encode_game_board_definition(
    GameBoardDefinition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_game_board_cell(self.playableCells, serializer);
    sse_encode_list_game_piece(self.startingPieces, serializer);
  }

  @protected
  void sse_encode_game_direction(GameDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_match_phase(
    GameMatchPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_move(GameMove self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pieceId, serializer);
    sse_encode_game_direction(self.direction, serializer);
  }

  @protected
  void sse_encode_game_piece(GamePiece self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.id, serializer);
    sse_encode_game_player(self.owner, serializer);
    sse_encode_u_8(self.x, serializer);
    sse_encode_u_8(self.y, serializer);
  }

  @protected
  void sse_encode_game_player(GamePlayer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_snapshot(GameSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_player(self.currentPlayer, serializer);
    sse_encode_list_game_tile(self.tiles, serializer);
    sse_encode_list_game_piece(self.pieces, serializer);
    sse_encode_opt_box_autoadd_counter_push_restriction(
      self.counterPush,
      serializer,
    );
    sse_encode_opt_box_autoadd_game_player(self.winner, serializer);
    sse_encode_opt_box_autoadd_game_win_reason(self.winReason, serializer);
    sse_encode_String(self.snapshotHash, serializer);
  }

  @protected
  void sse_encode_game_tile(GameTile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.x, serializer);
    sse_encode_u_8(self.y, serializer);
    sse_encode_game_tile_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_game_tile_kind(GameTileKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_win_reason(
    GameWinReason self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_game_board_cell(
    List<GameBoardCell> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_game_board_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_list_game_move(
    List<GameMove> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_game_move(item, serializer);
    }
  }

  @protected
  void sse_encode_list_game_piece(
    List<GamePiece> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_game_piece(item, serializer);
    }
  }

  @protected
  void sse_encode_list_game_tile(
    List<GameTile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_game_tile(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_match_snapshot(MatchSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_game_snapshot(self.round, serializer);
    sse_encode_list_game_piece(self.startingPieces, serializer);
    sse_encode_u_8(self.firstPlayerWins, serializer);
    sse_encode_u_8(self.secondPlayerWins, serializer);
    sse_encode_game_match_phase(self.phase, serializer);
    sse_encode_opt_box_autoadd_game_player(self.roundWinner, serializer);
    sse_encode_opt_box_autoadd_game_win_reason(self.roundWinReason, serializer);
    sse_encode_opt_box_autoadd_game_player(self.matchWinner, serializer);
    sse_encode_String(self.snapshotHash, serializer);
  }

  @protected
  void sse_encode_move_action_kind(
    MoveActionKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_move_resolution(
    MoveResolution self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_move_action_kind(self.actionKind, serializer);
    sse_encode_piece_travel(self.mover, serializer);
    sse_encode_opt_box_autoadd_piece_displacement(self.displaced, serializer);
    sse_encode_tile_transition(self.tileTransition, serializer);
  }

  @protected
  void sse_encode_move_result(MoveResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_match_snapshot(self.snapshot, serializer);
    sse_encode_move_resolution(self.resolution, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_counter_push_restriction(
    CounterPushRestriction? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_counter_push_restriction(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_game_direction(
    GameDirection? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_game_direction(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_game_move(
    GameMove? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_game_move(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_game_player(
    GamePlayer? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_game_player(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_game_win_reason(
    GameWinReason? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_game_win_reason(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_piece_displacement(
    PieceDisplacement? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_piece_displacement(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_piece_displacement(
    PieceDisplacement self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pieceId, serializer);
    sse_encode_u_8(self.fromX, serializer);
    sse_encode_u_8(self.fromY, serializer);
    sse_encode_opt_box_autoadd_u_8(self.toX, serializer);
    sse_encode_opt_box_autoadd_u_8(self.toY, serializer);
    sse_encode_opt_box_autoadd_game_direction(self.exitDirection, serializer);
  }

  @protected
  void sse_encode_piece_travel(PieceTravel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pieceId, serializer);
    sse_encode_u_8(self.fromX, serializer);
    sse_encode_u_8(self.fromY, serializer);
    sse_encode_u_8(self.toX, serializer);
    sse_encode_u_8(self.toY, serializer);
  }

  @protected
  void sse_encode_tile_transition(
    TileTransition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.x, serializer);
    sse_encode_u_8(self.y, serializer);
    sse_encode_game_tile_kind(self.from, serializer);
    sse_encode_game_tile_kind(self.to, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
