// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, non_constant_identifier_names, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:ttush_push/src/rust/api.dart';
import 'package:ttush_push/src/rust/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  CounterPushRestriction dco_decode_box_autoadd_counter_push_restriction(
    dynamic raw,
  );

  @protected
  GameMove dco_decode_box_autoadd_game_move(dynamic raw);

  @protected
  GamePlayer dco_decode_box_autoadd_game_player(dynamic raw);

  @protected
  GameSnapshot dco_decode_box_autoadd_game_snapshot(dynamic raw);

  @protected
  GameWinReason dco_decode_box_autoadd_game_win_reason(dynamic raw);

  @protected
  CounterPushRestriction dco_decode_counter_push_restriction(dynamic raw);

  @protected
  GameDirection dco_decode_game_direction(dynamic raw);

  @protected
  GameMove dco_decode_game_move(dynamic raw);

  @protected
  GamePiece dco_decode_game_piece(dynamic raw);

  @protected
  GamePlayer dco_decode_game_player(dynamic raw);

  @protected
  GameSnapshot dco_decode_game_snapshot(dynamic raw);

  @protected
  GameTile dco_decode_game_tile(dynamic raw);

  @protected
  GameTileKind dco_decode_game_tile_kind(dynamic raw);

  @protected
  GameWinReason dco_decode_game_win_reason(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<GameMove> dco_decode_list_game_move(dynamic raw);

  @protected
  List<GamePiece> dco_decode_list_game_piece(dynamic raw);

  @protected
  List<GameTile> dco_decode_list_game_tile(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  CounterPushRestriction? dco_decode_opt_box_autoadd_counter_push_restriction(
    dynamic raw,
  );

  @protected
  GamePlayer? dco_decode_opt_box_autoadd_game_player(dynamic raw);

  @protected
  GameWinReason? dco_decode_opt_box_autoadd_game_win_reason(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  CounterPushRestriction sse_decode_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GameMove sse_decode_box_autoadd_game_move(SseDeserializer deserializer);

  @protected
  GamePlayer sse_decode_box_autoadd_game_player(SseDeserializer deserializer);

  @protected
  GameSnapshot sse_decode_box_autoadd_game_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GameWinReason sse_decode_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  );

  @protected
  CounterPushRestriction sse_decode_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GameDirection sse_decode_game_direction(SseDeserializer deserializer);

  @protected
  GameMove sse_decode_game_move(SseDeserializer deserializer);

  @protected
  GamePiece sse_decode_game_piece(SseDeserializer deserializer);

  @protected
  GamePlayer sse_decode_game_player(SseDeserializer deserializer);

  @protected
  GameSnapshot sse_decode_game_snapshot(SseDeserializer deserializer);

  @protected
  GameTile sse_decode_game_tile(SseDeserializer deserializer);

  @protected
  GameTileKind sse_decode_game_tile_kind(SseDeserializer deserializer);

  @protected
  GameWinReason sse_decode_game_win_reason(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<GameMove> sse_decode_list_game_move(SseDeserializer deserializer);

  @protected
  List<GamePiece> sse_decode_list_game_piece(SseDeserializer deserializer);

  @protected
  List<GameTile> sse_decode_list_game_tile(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  CounterPushRestriction? sse_decode_opt_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GamePlayer? sse_decode_opt_box_autoadd_game_player(
    SseDeserializer deserializer,
  );

  @protected
  GameWinReason? sse_decode_opt_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_move(
    GameMove self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_player(
    GamePlayer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_snapshot(
    GameSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_win_reason(
    GameWinReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_direction(GameDirection self, SseSerializer serializer);

  @protected
  void sse_encode_game_move(GameMove self, SseSerializer serializer);

  @protected
  void sse_encode_game_piece(GamePiece self, SseSerializer serializer);

  @protected
  void sse_encode_game_player(GamePlayer self, SseSerializer serializer);

  @protected
  void sse_encode_game_snapshot(GameSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_game_tile(GameTile self, SseSerializer serializer);

  @protected
  void sse_encode_game_tile_kind(GameTileKind self, SseSerializer serializer);

  @protected
  void sse_encode_game_win_reason(GameWinReason self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_move(List<GameMove> self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_piece(
    List<GamePiece> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_tile(List<GameTile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_counter_push_restriction(
    CounterPushRestriction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_player(
    GamePlayer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_win_reason(
    GameWinReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;
}
