// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BotPolicy dco_decode_bot_policy(dynamic raw);

  @protected
  CounterPushRestriction dco_decode_box_autoadd_counter_push_restriction(
    dynamic raw,
  );

  @protected
  GameBoardDefinition dco_decode_box_autoadd_game_board_definition(dynamic raw);

  @protected
  GameDirection dco_decode_box_autoadd_game_direction(dynamic raw);

  @protected
  GameMove dco_decode_box_autoadd_game_move(dynamic raw);

  @protected
  GamePlayer dco_decode_box_autoadd_game_player(dynamic raw);

  @protected
  GameWinReason dco_decode_box_autoadd_game_win_reason(dynamic raw);

  @protected
  MatchSnapshot dco_decode_box_autoadd_match_snapshot(dynamic raw);

  @protected
  PieceDisplacement dco_decode_box_autoadd_piece_displacement(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  CounterPushRestriction dco_decode_counter_push_restriction(dynamic raw);

  @protected
  GameBoardCell dco_decode_game_board_cell(dynamic raw);

  @protected
  GameBoardDefinition dco_decode_game_board_definition(dynamic raw);

  @protected
  GameDirection dco_decode_game_direction(dynamic raw);

  @protected
  GameMatchPhase dco_decode_game_match_phase(dynamic raw);

  @protected
  GameMove dco_decode_game_move(dynamic raw);

  @protected
  GamePiece dco_decode_game_piece(dynamic raw);

  @protected
  GamePlayer dco_decode_game_player(dynamic raw);

  @protected
  GameSnapshot dco_decode_game_snapshot(dynamic raw);

  @protected
  GameTile dco_decode_game_tile(dynamic raw);

  @protected
  GameTileKind dco_decode_game_tile_kind(dynamic raw);

  @protected
  GameWinReason dco_decode_game_win_reason(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<GameBoardCell> dco_decode_list_game_board_cell(dynamic raw);

  @protected
  List<GameMove> dco_decode_list_game_move(dynamic raw);

  @protected
  List<GamePiece> dco_decode_list_game_piece(dynamic raw);

  @protected
  List<GameTile> dco_decode_list_game_tile(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MatchSnapshot dco_decode_match_snapshot(dynamic raw);

  @protected
  MoveActionKind dco_decode_move_action_kind(dynamic raw);

  @protected
  MoveResolution dco_decode_move_resolution(dynamic raw);

  @protected
  MoveResult dco_decode_move_result(dynamic raw);

  @protected
  CounterPushRestriction? dco_decode_opt_box_autoadd_counter_push_restriction(
    dynamic raw,
  );

  @protected
  GameDirection? dco_decode_opt_box_autoadd_game_direction(dynamic raw);

  @protected
  GameMove? dco_decode_opt_box_autoadd_game_move(dynamic raw);

  @protected
  GamePlayer? dco_decode_opt_box_autoadd_game_player(dynamic raw);

  @protected
  GameWinReason? dco_decode_opt_box_autoadd_game_win_reason(dynamic raw);

  @protected
  PieceDisplacement? dco_decode_opt_box_autoadd_piece_displacement(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  PieceDisplacement dco_decode_piece_displacement(dynamic raw);

  @protected
  PieceTravel dco_decode_piece_travel(dynamic raw);

  @protected
  TileTransition dco_decode_tile_transition(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BotPolicy sse_decode_bot_policy(SseDeserializer deserializer);

  @protected
  CounterPushRestriction sse_decode_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GameBoardDefinition sse_decode_box_autoadd_game_board_definition(
    SseDeserializer deserializer,
  );

  @protected
  GameDirection sse_decode_box_autoadd_game_direction(
    SseDeserializer deserializer,
  );

  @protected
  GameMove sse_decode_box_autoadd_game_move(SseDeserializer deserializer);

  @protected
  GamePlayer sse_decode_box_autoadd_game_player(SseDeserializer deserializer);

  @protected
  GameWinReason sse_decode_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  );

  @protected
  MatchSnapshot sse_decode_box_autoadd_match_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PieceDisplacement sse_decode_box_autoadd_piece_displacement(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  CounterPushRestriction sse_decode_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GameBoardCell sse_decode_game_board_cell(SseDeserializer deserializer);

  @protected
  GameBoardDefinition sse_decode_game_board_definition(
    SseDeserializer deserializer,
  );

  @protected
  GameDirection sse_decode_game_direction(SseDeserializer deserializer);

  @protected
  GameMatchPhase sse_decode_game_match_phase(SseDeserializer deserializer);

  @protected
  GameMove sse_decode_game_move(SseDeserializer deserializer);

  @protected
  GamePiece sse_decode_game_piece(SseDeserializer deserializer);

  @protected
  GamePlayer sse_decode_game_player(SseDeserializer deserializer);

  @protected
  GameSnapshot sse_decode_game_snapshot(SseDeserializer deserializer);

  @protected
  GameTile sse_decode_game_tile(SseDeserializer deserializer);

  @protected
  GameTileKind sse_decode_game_tile_kind(SseDeserializer deserializer);

  @protected
  GameWinReason sse_decode_game_win_reason(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<GameBoardCell> sse_decode_list_game_board_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<GameMove> sse_decode_list_game_move(SseDeserializer deserializer);

  @protected
  List<GamePiece> sse_decode_list_game_piece(SseDeserializer deserializer);

  @protected
  List<GameTile> sse_decode_list_game_tile(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MatchSnapshot sse_decode_match_snapshot(SseDeserializer deserializer);

  @protected
  MoveActionKind sse_decode_move_action_kind(SseDeserializer deserializer);

  @protected
  MoveResolution sse_decode_move_resolution(SseDeserializer deserializer);

  @protected
  MoveResult sse_decode_move_result(SseDeserializer deserializer);

  @protected
  CounterPushRestriction? sse_decode_opt_box_autoadd_counter_push_restriction(
    SseDeserializer deserializer,
  );

  @protected
  GameDirection? sse_decode_opt_box_autoadd_game_direction(
    SseDeserializer deserializer,
  );

  @protected
  GameMove? sse_decode_opt_box_autoadd_game_move(SseDeserializer deserializer);

  @protected
  GamePlayer? sse_decode_opt_box_autoadd_game_player(
    SseDeserializer deserializer,
  );

  @protected
  GameWinReason? sse_decode_opt_box_autoadd_game_win_reason(
    SseDeserializer deserializer,
  );

  @protected
  PieceDisplacement? sse_decode_opt_box_autoadd_piece_displacement(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  PieceDisplacement sse_decode_piece_displacement(SseDeserializer deserializer);

  @protected
  PieceTravel sse_decode_piece_travel(SseDeserializer deserializer);

  @protected
  TileTransition sse_decode_tile_transition(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bot_policy(BotPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_board_definition(
    GameBoardDefinition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_direction(
    GameDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_move(
    GameMove self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_player(
    GamePlayer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_win_reason(
    GameWinReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_match_snapshot(
    MatchSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_piece_displacement(
    PieceDisplacement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_counter_push_restriction(
    CounterPushRestriction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_board_cell(GameBoardCell self, SseSerializer serializer);

  @protected
  void sse_encode_game_board_definition(
    GameBoardDefinition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_direction(GameDirection self, SseSerializer serializer);

  @protected
  void sse_encode_game_match_phase(
    GameMatchPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_move(GameMove self, SseSerializer serializer);

  @protected
  void sse_encode_game_piece(GamePiece self, SseSerializer serializer);

  @protected
  void sse_encode_game_player(GamePlayer self, SseSerializer serializer);

  @protected
  void sse_encode_game_snapshot(GameSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_game_tile(GameTile self, SseSerializer serializer);

  @protected
  void sse_encode_game_tile_kind(GameTileKind self, SseSerializer serializer);

  @protected
  void sse_encode_game_win_reason(GameWinReason self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_board_cell(
    List<GameBoardCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_move(List<GameMove> self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_piece(
    List<GamePiece> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_tile(List<GameTile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_match_snapshot(MatchSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_move_action_kind(
    MoveActionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_move_resolution(
    MoveResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_move_result(MoveResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_counter_push_restriction(
    CounterPushRestriction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_direction(
    GameDirection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_move(
    GameMove? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_player(
    GamePlayer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_game_win_reason(
    GameWinReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_piece_displacement(
    PieceDisplacement? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_piece_displacement(
    PieceDisplacement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piece_travel(PieceTravel self, SseSerializer serializer);

  @protected
  void sse_encode_tile_transition(
    TileTransition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
