// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -933160049;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__advance_round_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "advance_round",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_snapshot = <crate::api::MatchSnapshot>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::advance_round(api_snapshot)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__choose_bot_move_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "choose_bot_move",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_snapshot = <crate::api::MatchSnapshot>::sse_decode(&mut deserializer);
            let api_policy = <crate::api::BotPolicy>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::choose_bot_move(api_snapshot, api_policy)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__initial_match_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initial_match",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_board_definition =
                <crate::api::GameBoardDefinition>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::initial_match(api_board_definition)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__match_apply_move_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "match_apply_move",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_snapshot = <crate::api::MatchSnapshot>::sse_decode(&mut deserializer);
            let api_game_move = <crate::api::GameMove>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::match_apply_move(api_snapshot, api_game_move)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__match_legal_moves_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "match_legal_moves",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_snapshot = <crate::api::MatchSnapshot>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::match_legal_moves(api_snapshot)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::BotPolicy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::BotPolicy::Random,
            1 => crate::api::BotPolicy::Greedy,
            2 => crate::api::BotPolicy::Minimax,
            _ => unreachable!("Invalid variant for BotPolicy: {}", inner),
        };
    }
}

impl SseDecode for crate::api::CounterPushRestriction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pusherPieceId = <u8>::sse_decode(deserializer);
        let mut var_pushedPieceId = <u8>::sse_decode(deserializer);
        return crate::api::CounterPushRestriction {
            pusher_piece_id: var_pusherPieceId,
            pushed_piece_id: var_pushedPieceId,
        };
    }
}

impl SseDecode for crate::api::GameBoardCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <u8>::sse_decode(deserializer);
        let mut var_y = <u8>::sse_decode(deserializer);
        return crate::api::GameBoardCell { x: var_x, y: var_y };
    }
}

impl SseDecode for crate::api::GameBoardDefinition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_playableCells = <Vec<crate::api::GameBoardCell>>::sse_decode(deserializer);
        let mut var_startingPieces = <Vec<crate::api::GamePiece>>::sse_decode(deserializer);
        return crate::api::GameBoardDefinition {
            playable_cells: var_playableCells,
            starting_pieces: var_startingPieces,
        };
    }
}

impl SseDecode for crate::api::GameDirection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GameDirection::Up,
            1 => crate::api::GameDirection::Down,
            2 => crate::api::GameDirection::Left,
            3 => crate::api::GameDirection::Right,
            _ => unreachable!("Invalid variant for GameDirection: {}", inner),
        };
    }
}

impl SseDecode for crate::api::GameMatchPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GameMatchPhase::Playing,
            1 => crate::api::GameMatchPhase::RoundOver,
            2 => crate::api::GameMatchPhase::MatchOver,
            _ => unreachable!("Invalid variant for GameMatchPhase: {}", inner),
        };
    }
}

impl SseDecode for crate::api::GameMove {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pieceId = <u8>::sse_decode(deserializer);
        let mut var_direction = <crate::api::GameDirection>::sse_decode(deserializer);
        return crate::api::GameMove {
            piece_id: var_pieceId,
            direction: var_direction,
        };
    }
}

impl SseDecode for crate::api::GamePiece {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u8>::sse_decode(deserializer);
        let mut var_owner = <crate::api::GamePlayer>::sse_decode(deserializer);
        let mut var_x = <u8>::sse_decode(deserializer);
        let mut var_y = <u8>::sse_decode(deserializer);
        return crate::api::GamePiece {
            id: var_id,
            owner: var_owner,
            x: var_x,
            y: var_y,
        };
    }
}

impl SseDecode for crate::api::GamePlayer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GamePlayer::First,
            1 => crate::api::GamePlayer::Second,
            _ => unreachable!("Invalid variant for GamePlayer: {}", inner),
        };
    }
}

impl SseDecode for crate::api::GameSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentPlayer = <crate::api::GamePlayer>::sse_decode(deserializer);
        let mut var_tiles = <Vec<crate::api::GameTile>>::sse_decode(deserializer);
        let mut var_pieces = <Vec<crate::api::GamePiece>>::sse_decode(deserializer);
        let mut var_counterPush =
            <Option<crate::api::CounterPushRestriction>>::sse_decode(deserializer);
        let mut var_winner = <Option<crate::api::GamePlayer>>::sse_decode(deserializer);
        let mut var_winReason = <Option<crate::api::GameWinReason>>::sse_decode(deserializer);
        let mut var_snapshotHash = <String>::sse_decode(deserializer);
        return crate::api::GameSnapshot {
            current_player: var_currentPlayer,
            tiles: var_tiles,
            pieces: var_pieces,
            counter_push: var_counterPush,
            winner: var_winner,
            win_reason: var_winReason,
            snapshot_hash: var_snapshotHash,
        };
    }
}

impl SseDecode for crate::api::GameTile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <u8>::sse_decode(deserializer);
        let mut var_y = <u8>::sse_decode(deserializer);
        let mut var_kind = <crate::api::GameTileKind>::sse_decode(deserializer);
        return crate::api::GameTile {
            x: var_x,
            y: var_y,
            kind: var_kind,
        };
    }
}

impl SseDecode for crate::api::GameTileKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GameTileKind::Normal,
            1 => crate::api::GameTileKind::Damaged,
            2 => crate::api::GameTileKind::Hole,
            _ => unreachable!("Invalid variant for GameTileKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::GameWinReason {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GameWinReason::Knockout,
            1 => crate::api::GameWinReason::Immobilization,
            _ => unreachable!("Invalid variant for GameWinReason: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::GameBoardCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GameBoardCell>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::GameMove> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GameMove>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::GamePiece> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GamePiece>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::GameTile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GameTile>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::MatchSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_round = <crate::api::GameSnapshot>::sse_decode(deserializer);
        let mut var_startingPieces = <Vec<crate::api::GamePiece>>::sse_decode(deserializer);
        let mut var_firstPlayerWins = <u8>::sse_decode(deserializer);
        let mut var_secondPlayerWins = <u8>::sse_decode(deserializer);
        let mut var_phase = <crate::api::GameMatchPhase>::sse_decode(deserializer);
        let mut var_roundWinner = <Option<crate::api::GamePlayer>>::sse_decode(deserializer);
        let mut var_roundWinReason = <Option<crate::api::GameWinReason>>::sse_decode(deserializer);
        let mut var_matchWinner = <Option<crate::api::GamePlayer>>::sse_decode(deserializer);
        let mut var_snapshotHash = <String>::sse_decode(deserializer);
        return crate::api::MatchSnapshot {
            round: var_round,
            starting_pieces: var_startingPieces,
            first_player_wins: var_firstPlayerWins,
            second_player_wins: var_secondPlayerWins,
            phase: var_phase,
            round_winner: var_roundWinner,
            round_win_reason: var_roundWinReason,
            match_winner: var_matchWinner,
            snapshot_hash: var_snapshotHash,
        };
    }
}

impl SseDecode for crate::api::MoveActionKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::MoveActionKind::Normal,
            1 => crate::api::MoveActionKind::Push,
            _ => unreachable!("Invalid variant for MoveActionKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::MoveResolution {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_actionKind = <crate::api::MoveActionKind>::sse_decode(deserializer);
        let mut var_mover = <crate::api::PieceTravel>::sse_decode(deserializer);
        let mut var_displaced = <Option<crate::api::PieceDisplacement>>::sse_decode(deserializer);
        let mut var_tileTransition = <crate::api::TileTransition>::sse_decode(deserializer);
        return crate::api::MoveResolution {
            action_kind: var_actionKind,
            mover: var_mover,
            displaced: var_displaced,
            tile_transition: var_tileTransition,
        };
    }
}

impl SseDecode for crate::api::MoveResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_snapshot = <crate::api::MatchSnapshot>::sse_decode(deserializer);
        let mut var_resolution = <crate::api::MoveResolution>::sse_decode(deserializer);
        return crate::api::MoveResult {
            snapshot: var_snapshot,
            resolution: var_resolution,
        };
    }
}

impl SseDecode for Option<crate::api::CounterPushRestriction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::CounterPushRestriction>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::GameDirection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::GameDirection>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::GameMove> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::GameMove>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::GamePlayer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::GamePlayer>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::GameWinReason> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::GameWinReason>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::PieceDisplacement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::PieceDisplacement>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::PieceDisplacement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pieceId = <u8>::sse_decode(deserializer);
        let mut var_fromX = <u8>::sse_decode(deserializer);
        let mut var_fromY = <u8>::sse_decode(deserializer);
        let mut var_toX = <Option<u8>>::sse_decode(deserializer);
        let mut var_toY = <Option<u8>>::sse_decode(deserializer);
        let mut var_exitDirection = <Option<crate::api::GameDirection>>::sse_decode(deserializer);
        return crate::api::PieceDisplacement {
            piece_id: var_pieceId,
            from_x: var_fromX,
            from_y: var_fromY,
            to_x: var_toX,
            to_y: var_toY,
            exit_direction: var_exitDirection,
        };
    }
}

impl SseDecode for crate::api::PieceTravel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pieceId = <u8>::sse_decode(deserializer);
        let mut var_fromX = <u8>::sse_decode(deserializer);
        let mut var_fromY = <u8>::sse_decode(deserializer);
        let mut var_toX = <u8>::sse_decode(deserializer);
        let mut var_toY = <u8>::sse_decode(deserializer);
        return crate::api::PieceTravel {
            piece_id: var_pieceId,
            from_x: var_fromX,
            from_y: var_fromY,
            to_x: var_toX,
            to_y: var_toY,
        };
    }
}

impl SseDecode for crate::api::TileTransition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <u8>::sse_decode(deserializer);
        let mut var_y = <u8>::sse_decode(deserializer);
        let mut var_from = <crate::api::GameTileKind>::sse_decode(deserializer);
        let mut var_to = <crate::api::GameTileKind>::sse_decode(deserializer);
        return crate::api::TileTransition {
            x: var_x,
            y: var_y,
            from: var_from,
            to: var_to,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__advance_round_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__choose_bot_move_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__initial_match_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__match_apply_move_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__match_legal_moves_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::BotPolicy {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Random => 0.into_dart(),
            Self::Greedy => 1.into_dart(),
            Self::Minimax => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::BotPolicy {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::BotPolicy> for crate::api::BotPolicy {
    fn into_into_dart(self) -> crate::api::BotPolicy {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CounterPushRestriction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pusher_piece_id.into_into_dart().into_dart(),
            self.pushed_piece_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::CounterPushRestriction
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CounterPushRestriction>
    for crate::api::CounterPushRestriction
{
    fn into_into_dart(self) -> crate::api::CounterPushRestriction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameBoardCell {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameBoardCell {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameBoardCell> for crate::api::GameBoardCell {
    fn into_into_dart(self) -> crate::api::GameBoardCell {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameBoardDefinition {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.playable_cells.into_into_dart().into_dart(),
            self.starting_pieces.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::GameBoardDefinition
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameBoardDefinition>
    for crate::api::GameBoardDefinition
{
    fn into_into_dart(self) -> crate::api::GameBoardDefinition {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameDirection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Up => 0.into_dart(),
            Self::Down => 1.into_dart(),
            Self::Left => 2.into_dart(),
            Self::Right => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameDirection {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameDirection> for crate::api::GameDirection {
    fn into_into_dart(self) -> crate::api::GameDirection {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameMatchPhase {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Playing => 0.into_dart(),
            Self::RoundOver => 1.into_dart(),
            Self::MatchOver => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameMatchPhase {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameMatchPhase> for crate::api::GameMatchPhase {
    fn into_into_dart(self) -> crate::api::GameMatchPhase {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameMove {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.piece_id.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameMove {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameMove> for crate::api::GameMove {
    fn into_into_dart(self) -> crate::api::GameMove {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GamePiece {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.owner.into_into_dart().into_dart(),
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GamePiece {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GamePiece> for crate::api::GamePiece {
    fn into_into_dart(self) -> crate::api::GamePiece {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GamePlayer {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::First => 0.into_dart(),
            Self::Second => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GamePlayer {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GamePlayer> for crate::api::GamePlayer {
    fn into_into_dart(self) -> crate::api::GamePlayer {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_player.into_into_dart().into_dart(),
            self.tiles.into_into_dart().into_dart(),
            self.pieces.into_into_dart().into_dart(),
            self.counter_push.into_into_dart().into_dart(),
            self.winner.into_into_dart().into_dart(),
            self.win_reason.into_into_dart().into_dart(),
            self.snapshot_hash.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameSnapshot> for crate::api::GameSnapshot {
    fn into_into_dart(self) -> crate::api::GameSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameTile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameTile {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameTile> for crate::api::GameTile {
    fn into_into_dart(self) -> crate::api::GameTile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameTileKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Normal => 0.into_dart(),
            Self::Damaged => 1.into_dart(),
            Self::Hole => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameTileKind {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameTileKind> for crate::api::GameTileKind {
    fn into_into_dart(self) -> crate::api::GameTileKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GameWinReason {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Knockout => 0.into_dart(),
            Self::Immobilization => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GameWinReason {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GameWinReason> for crate::api::GameWinReason {
    fn into_into_dart(self) -> crate::api::GameWinReason {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MatchSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.round.into_into_dart().into_dart(),
            self.starting_pieces.into_into_dart().into_dart(),
            self.first_player_wins.into_into_dart().into_dart(),
            self.second_player_wins.into_into_dart().into_dart(),
            self.phase.into_into_dart().into_dart(),
            self.round_winner.into_into_dart().into_dart(),
            self.round_win_reason.into_into_dart().into_dart(),
            self.match_winner.into_into_dart().into_dart(),
            self.snapshot_hash.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MatchSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MatchSnapshot> for crate::api::MatchSnapshot {
    fn into_into_dart(self) -> crate::api::MatchSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MoveActionKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Normal => 0.into_dart(),
            Self::Push => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MoveActionKind {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MoveActionKind> for crate::api::MoveActionKind {
    fn into_into_dart(self) -> crate::api::MoveActionKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MoveResolution {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.action_kind.into_into_dart().into_dart(),
            self.mover.into_into_dart().into_dart(),
            self.displaced.into_into_dart().into_dart(),
            self.tile_transition.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MoveResolution {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MoveResolution> for crate::api::MoveResolution {
    fn into_into_dart(self) -> crate::api::MoveResolution {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MoveResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.snapshot.into_into_dart().into_dart(),
            self.resolution.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MoveResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MoveResult> for crate::api::MoveResult {
    fn into_into_dart(self) -> crate::api::MoveResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PieceDisplacement {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.piece_id.into_into_dart().into_dart(),
            self.from_x.into_into_dart().into_dart(),
            self.from_y.into_into_dart().into_dart(),
            self.to_x.into_into_dart().into_dart(),
            self.to_y.into_into_dart().into_dart(),
            self.exit_direction.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::PieceDisplacement {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PieceDisplacement>
    for crate::api::PieceDisplacement
{
    fn into_into_dart(self) -> crate::api::PieceDisplacement {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PieceTravel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.piece_id.into_into_dart().into_dart(),
            self.from_x.into_into_dart().into_dart(),
            self.from_y.into_into_dart().into_dart(),
            self.to_x.into_into_dart().into_dart(),
            self.to_y.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::PieceTravel {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PieceTravel> for crate::api::PieceTravel {
    fn into_into_dart(self) -> crate::api::PieceTravel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::TileTransition {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.from.into_into_dart().into_dart(),
            self.to.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::TileTransition {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::TileTransition> for crate::api::TileTransition {
    fn into_into_dart(self) -> crate::api::TileTransition {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::BotPolicy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::BotPolicy::Random => 0,
                crate::api::BotPolicy::Greedy => 1,
                crate::api::BotPolicy::Minimax => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::CounterPushRestriction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.pusher_piece_id, serializer);
        <u8>::sse_encode(self.pushed_piece_id, serializer);
    }
}

impl SseEncode for crate::api::GameBoardCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.x, serializer);
        <u8>::sse_encode(self.y, serializer);
    }
}

impl SseEncode for crate::api::GameBoardDefinition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::GameBoardCell>>::sse_encode(self.playable_cells, serializer);
        <Vec<crate::api::GamePiece>>::sse_encode(self.starting_pieces, serializer);
    }
}

impl SseEncode for crate::api::GameDirection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GameDirection::Up => 0,
                crate::api::GameDirection::Down => 1,
                crate::api::GameDirection::Left => 2,
                crate::api::GameDirection::Right => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::GameMatchPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GameMatchPhase::Playing => 0,
                crate::api::GameMatchPhase::RoundOver => 1,
                crate::api::GameMatchPhase::MatchOver => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::GameMove {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.piece_id, serializer);
        <crate::api::GameDirection>::sse_encode(self.direction, serializer);
    }
}

impl SseEncode for crate::api::GamePiece {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.id, serializer);
        <crate::api::GamePlayer>::sse_encode(self.owner, serializer);
        <u8>::sse_encode(self.x, serializer);
        <u8>::sse_encode(self.y, serializer);
    }
}

impl SseEncode for crate::api::GamePlayer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GamePlayer::First => 0,
                crate::api::GamePlayer::Second => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::GameSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::GamePlayer>::sse_encode(self.current_player, serializer);
        <Vec<crate::api::GameTile>>::sse_encode(self.tiles, serializer);
        <Vec<crate::api::GamePiece>>::sse_encode(self.pieces, serializer);
        <Option<crate::api::CounterPushRestriction>>::sse_encode(self.counter_push, serializer);
        <Option<crate::api::GamePlayer>>::sse_encode(self.winner, serializer);
        <Option<crate::api::GameWinReason>>::sse_encode(self.win_reason, serializer);
        <String>::sse_encode(self.snapshot_hash, serializer);
    }
}

impl SseEncode for crate::api::GameTile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.x, serializer);
        <u8>::sse_encode(self.y, serializer);
        <crate::api::GameTileKind>::sse_encode(self.kind, serializer);
    }
}

impl SseEncode for crate::api::GameTileKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GameTileKind::Normal => 0,
                crate::api::GameTileKind::Damaged => 1,
                crate::api::GameTileKind::Hole => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::GameWinReason {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GameWinReason::Knockout => 0,
                crate::api::GameWinReason::Immobilization => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::GameBoardCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GameBoardCell>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::GameMove> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GameMove>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::GamePiece> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GamePiece>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::GameTile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GameTile>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::MatchSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::GameSnapshot>::sse_encode(self.round, serializer);
        <Vec<crate::api::GamePiece>>::sse_encode(self.starting_pieces, serializer);
        <u8>::sse_encode(self.first_player_wins, serializer);
        <u8>::sse_encode(self.second_player_wins, serializer);
        <crate::api::GameMatchPhase>::sse_encode(self.phase, serializer);
        <Option<crate::api::GamePlayer>>::sse_encode(self.round_winner, serializer);
        <Option<crate::api::GameWinReason>>::sse_encode(self.round_win_reason, serializer);
        <Option<crate::api::GamePlayer>>::sse_encode(self.match_winner, serializer);
        <String>::sse_encode(self.snapshot_hash, serializer);
    }
}

impl SseEncode for crate::api::MoveActionKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::MoveActionKind::Normal => 0,
                crate::api::MoveActionKind::Push => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::MoveResolution {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::MoveActionKind>::sse_encode(self.action_kind, serializer);
        <crate::api::PieceTravel>::sse_encode(self.mover, serializer);
        <Option<crate::api::PieceDisplacement>>::sse_encode(self.displaced, serializer);
        <crate::api::TileTransition>::sse_encode(self.tile_transition, serializer);
    }
}

impl SseEncode for crate::api::MoveResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::MatchSnapshot>::sse_encode(self.snapshot, serializer);
        <crate::api::MoveResolution>::sse_encode(self.resolution, serializer);
    }
}

impl SseEncode for Option<crate::api::CounterPushRestriction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::CounterPushRestriction>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::GameDirection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::GameDirection>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::GameMove> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::GameMove>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::GamePlayer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::GamePlayer>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::GameWinReason> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::GameWinReason>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::PieceDisplacement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::PieceDisplacement>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::PieceDisplacement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.piece_id, serializer);
        <u8>::sse_encode(self.from_x, serializer);
        <u8>::sse_encode(self.from_y, serializer);
        <Option<u8>>::sse_encode(self.to_x, serializer);
        <Option<u8>>::sse_encode(self.to_y, serializer);
        <Option<crate::api::GameDirection>>::sse_encode(self.exit_direction, serializer);
    }
}

impl SseEncode for crate::api::PieceTravel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.piece_id, serializer);
        <u8>::sse_encode(self.from_x, serializer);
        <u8>::sse_encode(self.from_y, serializer);
        <u8>::sse_encode(self.to_x, serializer);
        <u8>::sse_encode(self.to_y, serializer);
    }
}

impl SseEncode for crate::api::TileTransition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.x, serializer);
        <u8>::sse_encode(self.y, serializer);
        <crate::api::GameTileKind>::sse_encode(self.from, serializer);
        <crate::api::GameTileKind>::sse_encode(self.to, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
